language: java
jdk: oraclejdk9

install: TRUE

# Some Gradle nuance
before_cache:
  rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    $HOME/.gradle/caches/
    $HOME/.gradle/wrapper/

# DB services
services:
  sqlite3
  postgresql
  mysql

before_script:
  mysql -e "CREATE DATABASE sqlobtest"
  psql -U postgres -c "CREATE DATABASE sqlobtest"

script: ./gradlew build

# Generate and deploy Javadoc
before_deploy:
  ./gradlew javadoc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_TOKEN
  local_dir: build/docs
  on:
    branch: master

